kind: pipeline
name: default

steps:
- name: test
  image: golang
  volumes:
  - name: deps
    path: /go
  commands:
  - go test

- name: build
  image: golang
  volumes:
  - name: deps
    path: /go
  commands:
  - go build

- name: docker  
  image: plugins/docker
  settings:
#    username: kevinbacon
#    password: pa55word
    repo: localhost:5000
    tags: latest

volumes:
- name: deps
  temp: {}
